# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixelapps/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixelapps/optional


PRODUCT_PACKAGES += \
    SafetyRegulatoryInfo \
    DiagnosticsToolPrebuilt \
    DreamlinerUpdater \
    SSRestartDetector \
    PersistentBackgroundCameraServices \
    PersistentBackgroundServices \
    CccDkTimeSyncService \
    DeviceConnectivityServicePrebuilt_24.02.00 \
    UvExposureReporter \
