# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixelapps/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixelapps/common


PRODUCT_PACKAGES += \
    AdaptiveVPNPrebuilt-10307 \
    CreativeAssistant \
    DiagnosticsToolPrebuilt \
    DreamlinerPrebuilt \
    DreamlinerUpdater \
    PixelAIPrebuilt \
    RetailCorePrebuilt \
    RetailDemoGooglePrebuilt \
    SSRestartDetector \
    SatelliteGatewayPrebuilt \
    TipsPrebuilt_v5.2.0.595892729 \
    CccDkTimeSyncService \
    DeviceConnectivityServicePrebuilt_24.02.00 \
    PixelSatelliteService \
    SettingsGoogleFutureFaceEnroll \
    UvExposureReporter \
    VendorSatelliteService
