# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/PixelApps/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/PixelApps/common

PRODUCT_COPY_FILES += \
    vendor/PixelApps/common/proprietary/system_ext/etc/permissions/com.android.settings.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.settings.xml \
    vendor/PixelApps/common/proprietary/system_ext/etc/permissions/com.android.systemui.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.systemui.xml \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-BigNum/oat/arm64/SystemUIClocks-BigNum.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-BigNum/oat/arm64/SystemUIClocks-BigNum.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-BigNum/oat/arm64/SystemUIClocks-BigNum.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-BigNum/oat/arm64/SystemUIClocks-BigNum.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Calligraphy/oat/arm64/SystemUIClocks-Calligraphy.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Calligraphy/oat/arm64/SystemUIClocks-Calligraphy.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Calligraphy/oat/arm64/SystemUIClocks-Calligraphy.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Calligraphy/oat/arm64/SystemUIClocks-Calligraphy.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Flex/oat/arm64/SystemUIClocks-Flex.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Flex/oat/arm64/SystemUIClocks-Flex.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Flex/oat/arm64/SystemUIClocks-Flex.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Flex/oat/arm64/SystemUIClocks-Flex.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Growth/oat/arm64/SystemUIClocks-Growth.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Growth/oat/arm64/SystemUIClocks-Growth.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Growth/oat/arm64/SystemUIClocks-Growth.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Growth/oat/arm64/SystemUIClocks-Growth.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Inflate/oat/arm64/SystemUIClocks-Inflate.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Inflate/oat/arm64/SystemUIClocks-Inflate.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Inflate/oat/arm64/SystemUIClocks-Inflate.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Inflate/oat/arm64/SystemUIClocks-Inflate.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Metro/oat/arm64/SystemUIClocks-Metro.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Metro/oat/arm64/SystemUIClocks-Metro.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Metro/oat/arm64/SystemUIClocks-Metro.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Metro/oat/arm64/SystemUIClocks-Metro.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-NumOverlap/oat/arm64/SystemUIClocks-NumOverlap.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-NumOverlap/oat/arm64/SystemUIClocks-NumOverlap.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-NumOverlap/oat/arm64/SystemUIClocks-NumOverlap.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-NumOverlap/oat/arm64/SystemUIClocks-NumOverlap.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Weather/oat/arm64/SystemUIClocks-Weather.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Weather/oat/arm64/SystemUIClocks-Weather.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIClocks-Weather/oat/arm64/SystemUIClocks-Weather.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIClocks-Weather/oat/arm64/SystemUIClocks-Weather.vdex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIGoogle/oat/arm64/SystemUIGoogle.odex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIGoogle/oat/arm64/SystemUIGoogle.odex \
    vendor/PixelApps/common/proprietary/system_ext/priv-app/SystemUIGoogle/oat/arm64/SystemUIGoogle.vdex:$(TARGET_COPY_OUT_SYSTEM_EXT)/priv-app/SystemUIGoogle/oat/arm64/SystemUIGoogle.vdex

PRODUCT_PACKAGES += \
    SettingsGoogle \
    SystemUIClocks-BigNum \
    SystemUIClocks-Calligraphy \
    SystemUIClocks-Flex \
    SystemUIClocks-Growth \
    SystemUIClocks-Inflate \
    SystemUIClocks-Metro \
    SystemUIClocks-NumOverlap \
    SystemUIClocks-Weather \
    SystemUIGoogle
